import type { ReactNode } from 'react';

export enum AssetType {
  Drive = 'Google Drive',
  Docs = 'Google Docs',
  Sheets = 'Google Sheets',
  Slides = 'Google Slides',
  Calendar = 'Google Calendar',
  Forms = 'Google Forms',
  Keep = 'Google Keep',
  Chat = 'Google Chat',
  Logo = 'Logo'
}

export interface GeneratedAsset {
  type: AssetType;
  name: string;
  icon: ReactNode;
  url: string;
}

// Represents the detailed content for a pitch deck presentation
export interface PitchDeckContent {
  title: string;
  subtitle: string;
  problem: { title: string; content: string; };
  solution: { title: string; content: string; };
  targetMarket: { title: string; content: string; };
  team: { title: string; content: string; };
}

// Represents the full set of details generated by the AI
export interface ProjectDetails {
  projectName: string;
  projectObjective: string;
  brandIdentity: string;
  colorTheme: string;
  kickoffMeetingTitle: string;
  // Detailed content for each document
  projectProposal: string; // Full text content for the proposal doc
  projectPlan: string[][]; // Rows and columns for the project plan sheet
  budgetTracker: string[][]; // Rows and columns for the budget sheet
  pitchDeck: PitchDeckContent; // Structured content for the slides
  feedbackForm: string; // Questions for the feedback form, to be placed in a doc
  projectChecklist: string; // Checklist content for the Google Doc (Keep substitute)
}

export interface User {
  name: string;
  email: string;
  picture: string;
}

// Add this to make the Google Identity Services library available on the window object
declare global {
  interface Window {
    google?: {
      accounts: {
        oauth2: {
          initTokenClient: (config: google.accounts.oauth2.TokenClientConfig) => google.accounts.oauth2.TokenClient;
          revoke: (token: string, done: () => void) => void;
        };
      };
    };
  }
  namespace google.accounts.oauth2 {
      interface TokenClient {
        requestAccessToken: (overrideConfig?: Record<string, unknown>) => void;
      }
      interface TokenClientConfig {
        client_id: string;
        scope: string;
        callback: (tokenResponse: TokenResponse) => void;
        error_callback?: (error: unknown) => void;
      }
      interface TokenResponse {
        access_token: string;
        // ... other properties
      }
  }
}